plugins:
  flexiant:
    executor: central_deployment_agent
    source: https://github.com/buhanec/cloudify-flexiant-plugin/archive/master.zip

node_types:
  cloudify.flexiant.nodes.Server:
    derived_from: cloudify.nodes.Compute
    properties:
      auth: {}
      image:
        type: string
      network:
        type: string
      server_type:
        type: string
      cpu_count:
        type: integer
      ram_amount:
        type: integer
      manager_key:
        type: string
      public_keys:
        default: []
      install_agent:
        type: boolean
        default: true
      cloudify_agent:
        default: {}
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: flexiant.cfy.server.create
        start:
          implementation: flexiant.cfy.server.start
        stop:
          implementation: flexiant.cfy.server.stop
        delete:
          implementation: flexiant.cfy.server.delete
      cloudify.interfaces.validation:
        creation:
          implementation: flexiant.cfy.server.creation_validation
